# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icon.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(585, 655)
        Form.setStyleSheet("background: #57CC99;")
        self.music_label = QtWidgets.QLabel(Form)
        self.music_label.setGeometry(QtCore.QRect(180, 0, 329, 77))
        self.music_label.setStyleSheet("color: #000;\n"
"font-family: Inter;\n"
"font-size: 64px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.music_label.setText("")
        self.music_label.setPixmap(QtGui.QPixmap("Neuromusic (2).png"))
        self.music_label.setObjectName("music_label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 530, 585, 132))
        self.widget.setStyleSheet("border: 0.5px solid #000;\n"
"background: #38A3A5;\n"
"border-style: none;")
        self.widget.setObjectName("widget")
        self.id_lab = QtWidgets.QLabel(self.widget)
        self.id_lab.setGeometry(QtCore.QRect(0, 160, 61, 20))
        self.id_lab.setObjectName("id_lab")
        self.verif_label = QtWidgets.QLabel(self.widget)
        self.verif_label.setGeometry(QtCore.QRect(70, 160, 21, 20))
        self.verif_label.setObjectName("verif_label")
        self.varif_label_2 = QtWidgets.QLabel(self.widget)
        self.varif_label_2.setGeometry(QtCore.QRect(100, 160, 21, 20))
        self.varif_label_2.setObjectName("varif_label_2")
        self.music_slider = QtWidgets.QSlider(self.widget)
        self.music_slider.setGeometry(QtCore.QRect(90, 0, 391, 20))
        self.music_slider.setStyleSheet("stroke-width: 6px;\n"
"stroke: #0E1F5E;")
        self.music_slider.setOrientation(QtCore.Qt.Horizontal)
        self.music_slider.setObjectName("music_slider")
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setGeometry(QtCore.QRect(100, 30, 362, 69))
        self.widget_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.widget_8.setObjectName("widget_8")
        self.label_9 = QtWidgets.QLabel(self.widget_8)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 362, 69))
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Group 1.png"))
        self.label_9.setObjectName("label_9")
        self.next_button = QtWidgets.QPushButton(self.widget_8)
        self.next_button.setGeometry(QtCore.QRect(270, 0, 95, 66))
        self.next_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.next_button.setText("")
        self.next_button.setObjectName("next_button")
        self.back_button = QtWidgets.QPushButton(self.widget_8)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 95, 66))
        self.back_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.back_button.setText("")
        self.back_button.setObjectName("back_button")
        self.pausebutton = QtWidgets.QPushButton(self.widget_8)
        self.pausebutton.setGeometry(QtCore.QRect(140, 0, 69, 69))
        self.pausebutton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.pausebutton.setText("")
        self.pausebutton.setObjectName("pausebutton")
        self.label_9.raise_()
        self.pausebutton.raise_()
        self.back_button.raise_()
        self.next_button.raise_()
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 85, 531))
        self.frame.setStyleSheet("border: 0.5px solid #000;\n"
"background: #38A3A5;\n"
"border-style: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.menu_lab = QtWidgets.QLabel(self.frame)
        self.menu_lab.setGeometry(QtCore.QRect(20, 20, 50, 50))
        self.menu_lab.setStyleSheet("border-style: none;")
        self.menu_lab.setText("")
        self.menu_lab.setPixmap(QtGui.QPixmap("More square.png"))
        self.menu_lab.setObjectName("menu_lab")
        self.widget_6 = QtWidgets.QWidget(self.frame)
        self.widget_6.setGeometry(QtCore.QRect(20, 120, 61, 41))
        self.widget_6.setObjectName("widget_6")
        self.picture_label = QtWidgets.QLabel(self.widget_6)
        self.picture_label.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.picture_label.setStyleSheet("border-style: none;")
        self.picture_label.setText("")
        self.picture_label.setPixmap(QtGui.QPixmap("Cloud.png"))
        self.picture_label.setObjectName("picture_label")
        self.add_music = QtWidgets.QPushButton(self.widget_6)
        self.add_music.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.add_music.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-style: none;")
        self.add_music.setText("")
        self.add_music.setObjectName("add_music")
        self.widget_7 = QtWidgets.QWidget(self.frame)
        self.widget_7.setGeometry(QtCore.QRect(20, 210, 51, 41))
        self.widget_7.setObjectName("widget_7")
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 51, 41))
        self.label_8.setStyleSheet("border-style: none;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Music plate.svg"))
        self.label_8.setObjectName("label_8")
        self.my_playlist = QtWidgets.QPushButton(self.widget_7)
        self.my_playlist.setGeometry(QtCore.QRect(0, 0, 51, 41))
        self.my_playlist.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-style: none;")
        self.my_playlist.setText("")
        self.my_playlist.setObjectName("my_playlist")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(10, 300, 64, 64))
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("2577170 (1).png"))
        self.label.setObjectName("label")
        self.B_button = QtWidgets.QPushButton(self.widget_2)
        self.B_button.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.B_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.B_button.setText("")
        self.B_button.setObjectName("B_button")
        self.widget_6.raise_()
        self.widget_7.raise_()
        self.menu_lab.raise_()
        self.widget_2.raise_()
        self.condition_label = QtWidgets.QLabel(Form)
        self.condition_label.setGeometry(QtCore.QRect(30, 150, 453, 331))
        self.condition_label.setStyleSheet("color: #57CC99;\n"
"\n"
"font-family: Inter;\n"
"font-size: 64px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.condition_label.setText("")
        self.condition_label.setTextFormat(QtCore.Qt.AutoText)
        self.condition_label.setObjectName("condition_label")
        self.condition_label.raise_()
        self.music_label.raise_()
        self.widget.raise_()
        self.frame.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.id_lab.setText(_translate("Form", "id:"))
        self.verif_label.setText(_translate("Form", "TextLabel"))
        self.varif_label_2.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
