# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icon.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(585, 655)
        Form.setStyleSheet("background: #57CC99;")
        self.mus_name_label = QtWidgets.QLabel(Form)
        self.mus_name_label.setGeometry(QtCore.QRect(210, 0, 329, 77))
        self.mus_name_label.setStyleSheet("color: #000;\n"
"font-family: Inter;\n"
"font-size: 64px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.mus_name_label.setObjectName("mus_name_label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 530, 585, 132))
        self.widget.setStyleSheet("border: 0.5px solid #000;\n"
"background: #38A3A5;\n"
"border-style: none;")
        self.widget.setObjectName("widget")
        self.id_lab = QtWidgets.QLabel(self.widget)
        self.id_lab.setGeometry(QtCore.QRect(0, 160, 61, 20))
        self.id_lab.setObjectName("id_lab")
        self.verif_label = QtWidgets.QLabel(self.widget)
        self.verif_label.setGeometry(QtCore.QRect(70, 160, 21, 20))
        self.verif_label.setObjectName("verif_label")
        self.varif_label_2 = QtWidgets.QLabel(self.widget)
        self.varif_label_2.setGeometry(QtCore.QRect(100, 160, 21, 20))
        self.varif_label_2.setObjectName("varif_label_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(90, 30, 95, 66))
        self.widget_3.setObjectName("widget_3")
        self.back_button = QtWidgets.QPushButton(self.widget_3)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 95, 66))
        self.back_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.back_button.setText("")
        self.back_button.setObjectName("back_button")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 95, 66))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Downloads/Group 2.png"))
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.back_button.raise_()
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(370, 30, 95, 66))
        self.widget_4.setObjectName("widget_4")
        self.next_button = QtWidgets.QPushButton(self.widget_4)
        self.next_button.setGeometry(QtCore.QRect(0, 0, 95, 66))
        self.next_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.next_button.setText("")
        self.next_button.setObjectName("next_button")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 95, 66))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("photo_5204339240274613699_m.jpg"))
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.next_button.raise_()
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(510, 40, 51, 51))
        self.widget_5.setObjectName("widget_5")
        self.Valume_button = QtWidgets.QPushButton(self.widget_5)
        self.Valume_button.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.Valume_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.Valume_button.setText("")
        self.Valume_button.setObjectName("Valume_button")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../Downloads/Volume up.svg"))
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.Valume_button.raise_()
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(250, 30, 69, 69))
        self.widget_2.setObjectName("widget_2")
        self.pauseButton = QtWidgets.QPushButton(self.widget_2)
        self.pauseButton.setGeometry(QtCore.QRect(0, 0, 69, 69))
        self.pauseButton.setStyleSheet("fill: rgba(217, 217, 217, 0.00);\n"
"stroke-width: 3px;\n"
"stroke: #0E1F5E;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.pauseButton.setText("")
        self.pauseButton.setObjectName("pauseButton")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 69, 69))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Downloads/Ellipse 2.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 43, 43))
        self.label_2.setStyleSheet("div { border-radius: 20px; }")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Downloads/Polygon 6.svg"))
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.label_2.raise_()
        self.pauseButton.raise_()
        self.music_slider = QtWidgets.QSlider(self.widget)
        self.music_slider.setGeometry(QtCore.QRect(90, 0, 391, 20))
        self.music_slider.setStyleSheet("stroke-width: 6px;\n"
"stroke: #0E1F5E;")
        self.music_slider.setOrientation(QtCore.Qt.Horizontal)
        self.music_slider.setObjectName("music_slider")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 85, 531))
        self.frame.setStyleSheet("border: 0.5px solid #000;\n"
"background: #38A3A5;\n"
"border-style: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.menu_lab = QtWidgets.QLabel(self.frame)
        self.menu_lab.setGeometry(QtCore.QRect(20, 10, 50, 50))
        self.menu_lab.setStyleSheet("border-style: none;")
        self.menu_lab.setText("")
        self.menu_lab.setPixmap(QtGui.QPixmap("../Downloads/Untitled/Iconex/Light/More square.png"))
        self.menu_lab.setObjectName("menu_lab")
        self.widget_6 = QtWidgets.QWidget(self.frame)
        self.widget_6.setGeometry(QtCore.QRect(20, 120, 61, 41))
        self.widget_6.setObjectName("widget_6")
        self.picture_label = QtWidgets.QLabel(self.widget_6)
        self.picture_label.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.picture_label.setStyleSheet("border-style: none;")
        self.picture_label.setText("")
        self.picture_label.setPixmap(QtGui.QPixmap("photo_5204339240274613704_m.jpg"))
        self.picture_label.setObjectName("picture_label")
        self.add_music = QtWidgets.QPushButton(self.widget_6)
        self.add_music.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.add_music.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-style: none;")
        self.add_music.setText("")
        self.add_music.setObjectName("add_music")
        self.widget_7 = QtWidgets.QWidget(self.frame)
        self.widget_7.setGeometry(QtCore.QRect(20, 210, 51, 41))
        self.widget_7.setObjectName("widget_7")
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 51, 41))
        self.label_8.setStyleSheet("border-style: none;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Music plate.svg"))
        self.label_8.setObjectName("label_8")
        self.my_playlist = QtWidgets.QPushButton(self.widget_7)
        self.my_playlist.setGeometry(QtCore.QRect(0, 0, 51, 41))
        self.my_playlist.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-style: none;")
        self.my_playlist.setText("")
        self.my_playlist.setObjectName("my_playlist")
        self.condition_label = QtWidgets.QLabel(Form)
        self.condition_label.setGeometry(QtCore.QRect(130, 100, 453, 331))
        self.condition_label.setStyleSheet("color: #57CC99;\n"
"\n"
"font-family: Inter;\n"
"font-size: 64px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.condition_label.setText("")
        self.condition_label.setObjectName("condition_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mus_name_label.setText(_translate("Form", "TextLabel"))
        self.id_lab.setText(_translate("Form", "id:"))
        self.verif_label.setText(_translate("Form", "TextLabel"))
        self.varif_label_2.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
